version: "3.8"
services:
  backup:
    image: iluvatyr/volume-backup:1.1
    container_name: volume-backup
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - BACKUP_LOG_RETENTION=30
      - CRON_BACKUP_PERIOD=0 4 * * *
      #- BACKUP_DRYRUN=true # default=false
      #- UPTIME_PUSH_URL=https://uptime-kuma.yourdomain.com/api/push/D4oFi3gGXsXj?status=up&msg=OK&ping= (default not set)
    volumes:
      - /backup-bind-mount-for-docker-volumes:/backup        ## Bind mount as rsync target.
      - volume-backup-logs:/var/log/volume-backup                            ## (optional) volume (enable volume under volumes) or bind mount for rsync logs

      ## Mounting all docker volumes as readonly, which will be backed up to the /backup folder periodically
      - <your-docker-volume-1>:/volumes/<your-docker-volume-1>:ro
      - <your-docker-volume-2>:/volumes/<your-docker-volume-2>:ro
      - <same-compose-volume>:/volumes/<same-compose-volume>:ro

  same-compose-container:
    image: some_image:latest
    volumes:
      - same-compose-volume:/test
    restart: unless-stopped

volumes:
  volume-backup-logs:                                       ## (optional) comment this volume if you do not need logs persisting
  ## Volumes to be backed up
  <same-compose-volume>:
  ## Volumes to be backed up from other compose files (stacks in portainer)
  <your-docker-volume-1>:
    external: true
  <your-docker-volume-2>:
    external: true

